# Generated by Django 5.1.4 on 2024-12-06 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painting', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
    ]
